version: '3'

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8081:80"
    volumes:
      - ./app:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    container_name: php-apache
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.28
    platform: linux/amd64
    container_name: mysql-container
    ports:
      - "3316:3316"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      TZ: "Asia/Tokyo"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
